!define PRODUCT_NAME "VulkanVoxel"
!define PRODUCT_VERSION "3.0"
!define PRODUCT_PUBLISHER "K4pselll"
!define PRODUCT_WEB_SITE "https://github.com/K4pselll/VulkanVoxel"

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "VulkanVoxel-${PRODUCT_VERSION}-Setup.exe"
InstallDir "$PROGRAMFILES64\${PRODUCT_NAME}"
RequestExecutionLevel admin

Section "Install"
    SetOutPath "$INSTDIR"
    File "build\voxel.exe"
    File "C:\msys64\ucrt64\bin\libgcc_s_seh-1.dll"
    File "C:\msys64\ucrt64\bin\libstdc++-6.dll"
    File "C:\msys64\ucrt64\bin\libwinpthread-1.dll"
    SetOutPath "$INSTDIR\shaders"
    File "build\shaders\*.spv"
    SetOutPath "$INSTDIR"

    CreateDirectory "$SMPROGRAMS\${PRODUCT_NAME}"
    CreateShortCut "$SMPROGRAMS\${PRODUCT_NAME}\VulkanVoxel.lnk" "$INSTDIR\voxel.exe"
    CreateShortCut "$DESKTOP\VulkanVoxel.lnk" "$INSTDIR\voxel.exe"
    WriteUninstaller "$INSTDIR\Uninstall.exe"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "DisplayName" "${PRODUCT_NAME}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "UninstallString" "$INSTDIR\Uninstall.exe"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "DisplayVersion" "${PRODUCT_VERSION}"
    WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

Section "Uninstall"
    Delete "$INSTDIR\voxel.exe"
    Delete "$INSTDIR\libgcc_s_seh-1.dll"
    Delete "$INSTDIR\libstdc++-6.dll"
    Delete "$INSTDIR\libwinpthread-1.dll"
    Delete "$INSTDIR\shaders\*.spv"
    RMDir "$INSTDIR\shaders"
    Delete "$INSTDIR\Uninstall.exe"
    RMDir "$INSTDIR"
    Delete "$SMPROGRAMS\${PRODUCT_NAME}\VulkanVoxel.lnk"
    RMDir "$SMPROGRAMS\${PRODUCT_NAME}"
    Delete "$DESKTOP\VulkanVoxel.lnk"
    DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
SectionEnd
